# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_users_api_development

test:
  <<: *default
  database: simple_users_api_test

production:
  <<: *default
  database: simple_users_api_production
  username: simple_users_api
  password: <%= ENV['SIMPLE_USERS_API_DATABASE_PASSWORD'] %>
